"""
Django settings for Qshop project.

Generated by 'django-admin startproject' using Django 2.1.8.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '8&1u%oz5zbs8k-(m*6k6ecpqz_dprb#u_*-81tk6=c=la)bynt'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Buyer',
    'Seller',
    'djcelery'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'Qshop.middleware.MiddleWareTest',
]

# MIDDLEWARE = [
#     'django.middleware.cache.UpdateCacheMiddleware',
#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
#     'Qshop.middleware.MiddleWareTest',
#     'django.middleware.cache.FetchFromCacheMiddleware'
# ]全站缓存

ROOT_URLCONF = 'Qshop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Qshop.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
)
# STATIC_ROOT = os.path.join(BASE_DIR,"static") #静态文件的根目录，和STATICFILES_DIRS，MEDIA_URL，MEDIA_ROOT有冲突

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "static")



# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
#         'LOCATION':['127.0.0.1:11211']
#     }
# }
# CACHE_MIDDLEWARE_KEY_PREFIX = ''
# CACHE_MIDDLEWARE_SECONDS = 600
# CACHE_MIDDLEWARE_ALIAS = 'default'





alipay_public_key_string = '''-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwcwFN4yAlGqZzJOF8aFqLt4c6Fcy5EmLtr7oI5NSQG1BPaqUsHgDElref4dE2t15W0LCU7ZKYPuS9JXXlDlVUkJ0zVkIw3j/mpkB5+7bG6gbcZAMhzeXCgOgwBZzIg8licQpKjamVWOmGBxhMggEJLBM4k3v1zXPdai26a3DPvtSy/dJ7iTVFVxoSVQqJoIKo07eXZ28aTSC5dgbHPa+2OUqsJvT4Zbwt8flBYSTCHWGqVBU1WwBQtmIwRdfJjM9U7Jn5BUdaegPHfCMCE5KxwGd87RiZrTw19dKYDf7ObXq8x8SP43fhnoVrOUH7cWqNlJZktPPyVB37ubNar6bmQIDAQAB
-----END PUBLIC KEY-----'''

alipay_private_key_string = '''-----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEAwcwFN4yAlGqZzJOF8aFqLt4c6Fcy5EmLtr7oI5NSQG1BPaqUsHgDElref4dE2t15W0LCU7ZKYPuS9JXXlDlVUkJ0zVkIw3j/mpkB5+7bG6gbcZAMhzeXCgOgwBZzIg8licQpKjamVWOmGBxhMggEJLBM4k3v1zXPdai26a3DPvtSy/dJ7iTVFVxoSVQqJoIKo07eXZ28aTSC5dgbHPa+2OUqsJvT4Zbwt8flBYSTCHWGqVBU1WwBQtmIwRdfJjM9U7Jn5BUdaegPHfCMCE5KxwGd87RiZrTw19dKYDf7ObXq8x8SP43fhnoVrOUH7cWqNlJZktPPyVB37ubNar6bmQIDAQABAoIBAQCws8IeADJNIVXSvsBmrXMQAN4Cy19P3+9QVYl8xps8u2G9RIgGz6adWdV+Gmyh00cP+zMM+S2geEJqWSYTtKMjOg0eH4xqDy2gXNrsC1IlSYacaWfC8uD49I3iF5Yq+/ySPRX7s5C+UvnjCh1lbQG6IjY4Mi/53sqm0YrWTuWzygJ469HlkHHVrpfixu8r2ONzsAXdSVRFMoXf22JUZwV4jm7AfX0DnD0wWyuteeNmInGzvb4giDkLeyTX4yzgFovaUehEGEpZaOATMz1MWfYSFIzBJLTxhq5Yui3qtVBMSdWCQv1hPa0A8n2s0hZY8jSg/YKZMTm3e/EPEdgDiSXxAoGBAP/8WYz4HOsrEhkJJUZz7ltdLTKn2sLGuyUn74X0d8XLCcs6MfgiIy+1SgcaER9YuCA2Q6RNigo1xvC3UsfV9IM1D52TWvR9JW2BSacjwJlooQWipLW7DOwrRzY3n0ROGDYeUbQx4tjRvrsjmrkBN1L7yMDGPbB0KOigJS/x1DgnAoGBAMHOyKcSbtZWHEHpqrD2SEmnJIafDzVGhoxKhijBKHGB4zlsqXHotg0TUWo/HwAM3jeOE3NPW16OUHAHZy1yvjRiQ/sccRjcXTZE/DskTcxS76d+AO2kW5uYsxO1kEDg2GQEC4XB4MX4gh/HV47qU2+z7BkwtwMA0cXbXWN1uSY/AoGBAOtxuRP1qPOL++tXBBfWzWbvPoEW7hi0HLFCGAZHIlqkMu/fKNKm42IgBmSdzx3bxg6qmnBmeQ6HA+GnW9Y9rdV4WlJ+k+vHp0Me5RV7xsvS9jdurrwPvQUDkU4GvtBeW9p67H8mWxU9ZYZOayK6QZ5rwuu76kV/sZi0oz+D18OFAoGAJCYtxvvpMJFfM+whqmBFm3dRmMqSS52b+w7rdy6QHJvdhhh+goCldErmJKshXSEJUdNuTVO/9yMUXdEDrbZ5Q8wQYgYsEjcIK9cyNNXQrQvLJ7KY+bpuW9dfj42OGovV0NHwVEKValev7b2A12ddqLgmkYxElorQldcU1DhhEIECgYBxlMklF3Ij0nTyIRswmGwxP6B7zH+wKnCmWzzNSJugKu0P5MqP45WxfIJnmPNPlF19VD0MKa4P+/Ukp1Q5QviKS+ma38dtsFKNuEZqvZnV2vUAlPjXevn9Lxkqu5TIL9pA/lgtzkv0FnGmvfknD7nWZliLCgA0tPiityzE+E7xRA==
-----END RSA PRIVATE KEY-----'''

DingURL = 'https://oapi.dingtalk.com/robot/send?access_token=2b71ad426976dee9b68a135682796f402ad543965fbb16346fd4f043beed6d8a'

import djcelery

djcelery.setup_loader()
BROKER_URL = 'redis://127.0.0.1:6379/1'
CELERY_IMPORTS = ('CeleryTask.tasks')
CELERY_TIMEZONE = 'Asia/Shanghai'
CELERYBEAT_SCHEDULER = 'djcelery.schedulers.DatabaseScheduler'

from celery.schedules import crontab
from celery.schedules import timedelta

CELERYBEAT_SCHEDULE = {
    'u测试任务1': {
        'task': 'CeleryTask.tasks.sendDing',
        'schedule': timedelta(seconds=5)
    }
}

ERROR_PATH = os.path.join(BASE_DIR, 'error.log')
