# Generated by Django 2.1.8 on 2019-09-11 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Seller', '0004_goods_goods_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=32)),
                ('order_data', models.DateTimeField(auto_now=True)),
                ('order_status', models.IntegerField()),
                ('order_total', models.FloatField(blank=True, null=True)),
                ('order_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.LoginUser')),
            ],
        ),
    ]
