# Generated by Django 2.1.8 on 2019-09-11 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0004_goods_goods_description'),
        ('Buyer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_id', models.IntegerField()),
                ('goods_picture', models.CharField(max_length=32)),
                ('goods_name', models.CharField(max_length=32)),
                ('goods_count', models.IntegerField()),
                ('good_price', models.FloatField()),
                ('goods_total_price', models.FloatField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buyer.PayOrder')),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.LoginUser')),
            ],
        ),
    ]
