# Generated by Django 2.1.8 on 2019-09-16 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0003_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinfo',
            old_name='good_price',
            new_name='goods_price',
        ),
    ]
